name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

#    - name: configure
#      run: ./configure

    - name: Install dependencies
      run: make

#    - name: Run check
#      run: make check

#    - name: Run distcheck
#      run: make distcheck
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: hello
        path: binaries/

    - name: Install dependencies
      run: |
        sudo add-apt-repository --yes ppa:mir-team/dev
        sudo apt install --yes \
          build-essential \
          libapparmor-dev \
          libboost-iostreams-dev \
          libfreetype6-dev \
          libmiral-dev \
          libwayland-dev \
          ninja-build \
          pkg-config

    - name: Run TICS analysis
      uses: tiobe/tics-github-action@v3
      with:
        mode: client
        project: tests
        viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
        ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
        installTics: true
