name: TICS run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/azkaratea/ticsimg:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PKGTOKEN }}
        
    steps:
    - name: Checkout the project
      uses: actions/checkout@v4

    - name: Install dependencies
      run: apt-get update && apt-get install -y build-essential

    - name: Build the project
      run: make

    - name: Run TICS analysis with the script
      run: |
           set -x
           export TICSAUTHTOKEN="${{ secrets.TICSAUTHTOKEN }}"
           export PATH="/root/TICS/Wrapper/BuildServer:$PATH"
           export PATH="/root/TICS/Wrapper/Client:$PATH"
           export TICS="https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default"
           TICSQServer -project testimage -tmpdir /tmp/tics -branchdir .
